# Generated by Django 4.1.7 on 2023-08-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='image',
            field=models.ImageField(blank=True, upload_to='classe'),
        ),
    ]
