# Generated by Django 4.2.3 on 2023-07-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_commentaire_reponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='lesson',
            new_name='nom_lesson',
        ),
    ]
