# Generated by Django 4.1.7 on 2023-08-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_profile_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(choices=[('etudiant', 'etudiant'), ('enseignant', 'enseignant')], default='etudiant', max_length=100),
        ),
    ]
